### ISSUE TITLE
Problem: No way to proceed if password is forgotten

### ISSUE THREAD

**Issue by savvysuarez** [starcity-properties/starcity-web#253] opened 2016-08-04 22:06 UTC
I forgot my password and I can neither re-register with the same address or recover my previous password.  

![forgotten password](https://cloud.githubusercontent.com/assets/10428592/17419971/e712917e-5a54-11e6-977a-f4fa41dae1e8.png)

**Comment by jalehman** [comment] 2016-08-04 22:07
Duplicate of #56

**Closed by jalehman** 2016-08-04 22:07 UTC
