### ISSUE TITLE
Issue: Community Fitness Page

### ISSUE THREAD

**Issue by jondishotsky** [starcity-properties/starcity-web#229] opened 2016-08-02 02:08 UTC
From Sofia Svensk,

"LOOKS GREAT! One issue...

After I filled out the community fitness page - it shot me back to the sign in page, when you hit sign in, it takes you back to community fitness again. Second time around it worked though, maybe just take a look at it to make sure. 

Let me know if I can help more!"

**Comment by jalehman** [comment] 2016-08-02 15:43
Appears to be a duplicate of #222.

**Closed by jalehman** 2016-08-02 15:43 UTC
